### ISSUE TITLE
Dependencies issue

### ISSUE THREAD

**Issue by code4bin** [ribthegreat99OrN0P/Agile.NET-Deobfuscator-Latest#2]
Thank for your great solution! (I used the previous version).

Now I'm trying to compile this new version (using VB 2022) but it indicates the problem with "Echo.Platforms.AsmResolver".
I copied all "Echo" compiled files from "Washi1337", but there's no "Echo.Platforms.AsmResolver" resources.

Colud you please help?

**Comment by ribthegreat99OrN0P** [comment]
Hello, i have compiled all binaries for you please visit https://github.com/ribthegreat99OrN0P/Agile.NET-Deobfuscator-Latest/releases/tag/release
