### ISSUE TITLE
Some issues with some Clisecure .exe's

### ISSUE THREAD

**Issue by raithedavion** [ribthegreat99OrN0P/Agile.NET-Deobfuscator-Latest#3]
I was attempting to mess around and try and deobfuscate some code, and I keep getting errors.  

1)  I had to put an if statement around the "type.NestedTypes.First() in FindData.  It throws an error if the count is zero.  
2)  I had to change the name of the DotNetRT to what I see in my executable.  Maybe "contains" DotNetRT?
3)  With all that, it gets through decryptions/etc..to fail when writing the deobfuscated module.  

MemberNotImportedException: Member InitializeDelegate (0x02000026) was not imported into the module.

I'm no expert in this so I have no idea what this thing is doing in that regard :(

**Comment by ribthegreat99OrN0P** [comment]
some programs protected by agile contain different trademark global module type names, on default it is <AgileDotNet>. What protections are enabled in the target exe e.g cflow, str encryption, call protection, virtualization, etc..

**Comment by ribthegreat99OrN0P** [comment]
issue fixed in latest commit
