### ISSUE TITLE
Hi PE not Saves /help 

### ISSUE THREAD

**Issue by SyntaxEvg** [ribthegreat99OrN0P/Agile.NET-Deobfuscator-Latest#5]
![image](https://user-images.githubusercontent.com/94603687/147370828-747ab921-97e8-453d-b611-cafb256a6d19.png)

**Comment by ribthegreat99OrN0P** [comment]
This will be resolved in upcoming update/commit

**Comment by HPXCoder** [comment]
@ribthegreat99OrN0P  i have the same problem after clearing the delegate calls 
it say that all the deleted delegates was not into the module
