### ISSUE TITLE
Unhandled exception. System.AggregateException: Construction of the PE image failed with one or more errors. 

### ISSUE THREAD

**Issue by gagmeng** [ribthegreat99OrN0P/Agile.NET-Deobfuscator-Latest#7]
resolving assemblies from framework version : 4.0
started Call Resolver
started String Decryption
started ControlFlow
Unhandled exception. System.AggregateException: Construction of the PE image failed with one or more errors. (Member InitializeDelegate (0x02000013) was not imported into the module.) (Member ExitDelegate (0x02000014) was not imported into the module.) (Member System.Void <AgileDotNetRT>::Initialize() (0x0600008B) was not imported into the module.) (Member System.Void <AgileDotNetRT>::PostInitialize() (0x0600008C) was not imported into the module.) (Member System.Void <AgileDotNetRT>::Initialize() (0x0600008B) was not imported into the module.) (Member System.Void <AgileDotNetRT>::PostInitialize() (0x0600008C) was not imported into the module.) (Member System.Void <AgileDotNetRT>::Initialize() (0x0600008B) was not imported into the module.) (Member System.Void <AgileDotNetRT>::PostInitialize() (0x0600008C) was not imported into the module.) (Member System.Void <AgileDotNetRT>::Initialize() (0x0600008B) was not imported into the module.) (Member System.Void <AgileDotNetRT>::PostInitialize() (0x0600008C) was not imported into the module.) (Member System.Void <AgileDotNetRT>::Initialize() (0x0600008B) was not imported into the module.) (Member System.Void <AgileDotNetRT>::PostInitialize() (0x0600008C) was not imported into the module.) (Member System.Void <AgileDotNetRT>::Initialize() (0x0600008B) was not imported into the module.) (Member System.Void <AgileDotNetRT>::PostInitialize() (0x0600008C) was not imported into the module.) (Member System.Void <AgileDotNetRT>::Initialize() (0x0600008B) was not imported into the module.) (Member System.Void <AgileDotNetRT>::PostInitialize() (0x0600008C) was not imported into the module.) (Member System.Void <AgileDotNetRT>::Initialize() (0x0600008B) was not imported into the module.) (Member System.Void <AgileDotNetRT>::PostInitialize() (0x0600008C) was not imported into the module.) (Member System.Void <AgileDotNetRT>::Initialize() (0x0600008B) was not imported into the module.) (Member System.Void <AgileDotNetRT>::PostInitialize() (0x0600008C) was not imported into the module.) (Member System.Void <AgileDotNetRT>::Initialize() (0x0600008B) was not imported into the module.) (Member System.Void <AgileDotNetRT>::PostInitialize() (0x0600008C) was not imported into the module.) (Member System.Void <AgileDotNetRT>::Initialize() (0x0600008B) was not imported into the module.) (Member System.Void <AgileDotNetRT>::PostInitialize() (0x0600008C) was not imported into the module.) (Member System.Void <AgileDotNetRT>::Initialize() (0x0600008B) was not imported into the module.) (Member System.Void <AgileDotNetRT>::PostInitialize() (0x0600008C) was not imported into the module.) (Member System.Void <AgileDotNetRT>::Initialize() (0x0600008B) was not imported into the module.) (Member System.Void <AgileDotNetRT>::PostInitialize() (0x0600008C) was not imported into the module.) (Member System.Void <AgileDotNetRT>::Initialize() (0x0600008B) was not imported into the module.) (Member System.Void <AgileDotNetRT>::PostInitialize() (0x0600008C) was not imported into the module.) (Member System.Void <AgileDotNetRT>::Initialize() (0x0600008B) was not imported into the module.) (Member System.Void <AgileDotNetRT>::PostInitialize() (0x0600008C) was not imported into the module.)
 ---> AsmResolver.DotNet.Builder.Metadata.MemberNotImportedException: Member InitializeDelegate (0x02000013) was not imported into the module.
   --- End of inner exception stack trace ---
   at AsmResolver.DotNet.ModuleDefinition.ToPEImage(IPEImageBuilder imageBuilder)
   at AsmResolver.DotNet.ModuleDefinition.Write(IBinaryStreamWriter writer, IPEImageBuilder imageBuilder, IPEFileBuilder fileBuilder)
   at AsmResolver.DotNet.ModuleDefinition.Write(Stream outputStream, IPEImageBuilder imageBuilder, IPEFileBuilder fileBuilder)
   at AsmResolver.DotNet.ModuleDefinition.Write(String filePath, IPEImageBuilder imageBuilder, IPEFileBuilder fileBuilder)
   at Agile.NET_Deobfuscator_Updated.Program.Main(String[] file) in D:\Visual Studio Projects\AgileDeobfuscators\Agile.NET-Deobfuscator-Updated\Agile.NET-Deobfuscator-Updated\Agile.NET-Deobfuscator-Updated\Program.cs:line 52
 ---> (Inner Exception #1) AsmResolver.DotNet.Builder.Metadata.MemberNotImportedException: Member ExitDelegate (0x02000014) was not imported into the module.<---

 ---> (Inner Exception #2) AsmResolver.DotNet.Builder.Metadata.MemberNotImportedException: Member System.Void <AgileDotNetRT>::Initialize() (0x0600008B) was not imported into the module.<---

 ---> (Inner Exception #3) AsmResolver.DotNet.Builder.Metadata.MemberNotImportedException: Member System.Void <AgileDotNetRT>::PostInitialize() (0x0600008C) was not imported into the module.<---

**Comment by ribthegreat99OrN0P** [comment]
controlflow hasnt been completed, so disable it in the code
