### ISSUE TITLE
System.AggregateException: 'Construction of the PE image failed with one or more errors. 

### ISSUE THREAD

**Issue by HPXCoder** [ribthegreat99OrN0P/Agile.NET-Deobfuscator-Latest#8]
When Writing the Dll in  
Program.cs / LINE : 53 

            ctx.Assembly.ManifestModule.Write(Path.GetFileNameWithoutExtension(ctx.Path) + "-deob" +(ctx.Assembly.ManifestModule.IsILLibrary ? ".dll" : ".exe"), imageBuilder);

![555555555555](https://user-images.githubusercontent.com/31288493/150419165-19383356-f5d5-4816-aeb4-79433b6bb9db.PNG)

**Comment by HPXCoder** [comment]
@ribthegreat99OrN0P  ؟

**Comment by ribthegreat99OrN0P** [comment]
this is going to be fixed upcoming
